[package]
name = "polkadot-zombienet-sdk-tests"
version = "0.1.0"
description = "Zomebienet-sdk tests."
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
asset-hub-westend-runtime = { workspace = true }
codec = { workspace = true, features = ["derive"] }
cumulus-zombienet-sdk-helpers = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
pallet-revive = { workspace = true, features = ["std"] }
polkadot-primitives = { workspace = true, default-features = true }
serde = { workspace = true }
serde_json = { workspace = true }
sp-core = { workspace = true }
subxt = { workspace = true }
subxt-macro = { workspace = true, features = ["runtime-metadata-insecure-url"] }
subxt-signer = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-util = { workspace = true, features = ["time"] }
zombienet-sdk = { workspace = true }

[features]
zombie-metadata = []
zombie-ci = []

[build-dependencies]
substrate-build-script-utils = { workspace = true, default-features = true }
subwasmlib = { git = "https://github.com/chevdor/subwasm", rev = "v0.21.3" }
